name: Build and Deploy to k3s

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: chida511/flask-demo:latest
  NAMESPACE: devops-lab
  RELEASE_NAME: flask-demo

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build and push Docker image
      run: |
        docker build -t $IMAGE_NAME .
        docker push $IMAGE_NAME

    - name: Set up KUBECONFIG
      run: |
        mkdir -p ~/.kube
        echo "${{ secrets.KUBECONFIG }}" | base64 -d > ~/.kube/config
        chmod 600 ~/.kube/config

    - name: Install Helm
      uses: azure/setup-helm@v3
      with:
        version: v3.8.0

    - name: Deploy app with Helm
      run: |
        helm upgrade --install $RELEASE_NAME ./helm-chart --namespace $NAMESPACE --create-namespace
