name: Build and Deploy to k3s

on:
  push:
    branches:
      - main

env:
  DOCKER_IMAGE: flask-demo
  NAMESPACE: devops-lab
  RELEASE_NAME: flask-demo

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
    - name: 🧾 Checkout Code
      uses: actions/checkout@v3

    - name: 🔐 Docker Login
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: 🛠️ Build & Push Docker Image
      run: |
        IMAGE_NAME="${{ secrets.DOCKER_USERNAME }}/$DOCKER_IMAGE:latest"
        docker build -t $IMAGE_NAME .
        docker push $IMAGE_NAME
      env:
        IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/flask-demo:latest

    - name: 📁 Set up kubeconfig
      run: |
        mkdir -p ~/.kube
        echo "${{ secrets.KUBECONFIG }}" | base64 -d > ~/.kube/config
        chmod 600 ~/.kube/config

    - name: ⚙️ Install Helm
      uses: azure/setup-helm@v3
      with:
        version: v3.8.0

    - name: 🚀 Deploy with Helm to k3s
      run: |
        IMAGE_NAME="${{ secrets.DOCKER_USERNAME }}/$DOCKER_IMAGE:latest"
        helm upgrade --install $RELEASE_NAME ./helm-chart \
          --namespace $NAMESPACE \
          --create-namespace \
          --set image.repository=${{ secrets.DOCKER_USERNAME }}/$DOCKER_IMAGE \
          --set image.tag=latest \
          --wait
